version: 2.1

orbs:
  statie:
    orbs:
      node: circleci/node@0.0.8
    commands:
      get:
        parameters:
          source:
              type: string
          path:
              type: string
        steps:
          - run: STATIE_SOURCE=<<parameters.source>> get <<parameters.path>>
      
    jobs:
      setup:
        executor: node/default
        steps:
          - checkout
          - node/install-package-manager:
              npm: true
          - node/with-cache:
              cache-key: statie/package.json
              steps:
                - run: cd statie && sudo npm install -g
                - run: which get
      get:
        executor: node/default
        parameters:
          source:
              type: string
          path:
              type: string
        steps:
          - get:
              source: <<parameters.source>>
              path: <<parameters.path>>

jobs:
  setup-environment:
      docker:
        - image: circleci/node:11
      steps:
        - checkout
        - run: mkdir ~/my-state
        - save_cache:
              key: my-state
              paths: ~/my-state

workflows:
  push:
    jobs:
      - setup-environment
      - statie/setup
      - statie/get:
            source: ~/my-state
            path: counter.state