version: 2.1

jobs:
  increment-by-one:
      docker:
        - image: node:10
      steps:
        - run: ./call counter increment
        - run: [ `./read counter.state` = "1" ]

workflows:
  push:
    jobs:
      - increment-by-one