version: 2.1

orbs:
  statie:
    orbs:
      node: circleci/node@0.0.8
    jobs:
      setup:
        executor: node/default
        steps:
          - node/install-package-manager:
              yarn: true
          - checkout
          - node/with-cache:
              cache-key: statie/package.json
              steps:
                - run: cd statie && yarn global add

# jobs:
#   increment-by-one:
#       docker:
#         - image: node:10
#       steps:
#         - run: ./call counter increment
#         - run: "[ `./read counter.state` = \"1\" ]"

workflows:
  push:
    jobs:
      - statie/setup